id: app
title: SBD 4.0
type: project
version: 1.0
icon: app.png
introduction:
  format: markdown
  template: SBD 4.0
catalog:
  category: Secure By Design version 4.0
  vendor: Hologic
  vendor_url: http://hologic.com
  status: stub
  source_url: https://github.com/mjhillyer/GR_Apps
  description:
    short: |
      Secure Product Design Program.
    long: |
      Hologic Product Cyberseucity Program
      ====================================

      Provides Secure Product Design Program to enable a Secure by Design methodology.
  version: '1.0'
questions:
- id: dev_team_info
  title: Product Information
  type: module
  module-id: dev_team_info

