id: app
title: Hologic Product Cybersecurity Program
type: project
version: 1.2
icon: app.png
introduction:
  format: markdown
  template: "The goal of The Hologic Secure Product Design Program is to provide a
    Secure by Design methodology to the product engineering activities that span the
    entire product lifecycle from initial concept to product obsolescence. This allows
    the product development team to 'shift left' their security activities, allowing
    the inclusion of security features earlier in the development process. By shifting
    left, the cost to mitigate any security risk is significantly reduced.   \n"
input: []
output: []
catalog:
  category: Hologic
  vendor: Hologic
  vendor_url: http://hologic.com
  status: Operational
  source_url: https://github.com/mjhillyer/GR_Apps
  description:
    short: |
      Secure Product Design Program.
    long: |
      Provides Secure Product Design Program to enable a Secure by Design methodology.
  version: 1.2
questions:
- id: prod_metadata
title: Module 1 - Information about the Product and the Product Team
type: module
module-id: module_1

