id: app
title: Python Test
type: project
version: 1.3
icon: app.png
introduction: []
input: []
output: []
catalog: 
  category: Hologic
  vendor: Hologic
  vendor_url: http://hologic.com
  status: Operational
  source_url: https://github.com/mjhillyer/GR_Apps
  description:
    short: |
      test
    long: |
      tesssssssssssttttttt
  version: 1.3
questions:
- id: module_1
  title: Python Test
  type: module
  module-id: module_1

