id: app
title: Python Test
type: project
version: 1.3
icon: app.png
introduction: []
input: []
output: []
catalog: []
questions:
- id: module_1
  title: Python Test
  type: module
  module-id: module_1

