id: app
title: Hologic Product Cybersecurity Program
type: project
version: 1.6
icon: app.png
introduction:
  format: markdown
  template: Hologic Product Security Workflow
input: []
output: []
catalog:
  category: Secure By Design
  vendor: Hologic
  vendor_url: http://hologic.com
  status: stub
  source_url: https://github.com/mjhillyer/GR_Apps
  description:
    short: |
      Secure Product Design Program.
    long: |
      Provides a workflow to enable a Secure by Design methodology.
  version: 1.6
questions:
- id: module_1
  title: Module 1 - Information about the Product and the Product Team
  type: module
  module-id: module_1
- id: module_10
  title: Module 1S - Submit Data to Watchtower:Commander
  type: module
  module-id: module_10
- id: init_assessment
  title: Module 2 - Product Operational and Environmental Assessment
  type: module
  module-id: module_2
- id: post_market
  title: Module 3 - Post Market Support Plan
  type: module
  module-id: module_3
- id: min_requirements
  title: Module 4 - Minimum Security Requirements Assessment
  type: module
  module-id: module_4
- id: prod_controls
  title: Module 5 - Product Security Controls
  type: module
  module-id: module_5
- id: pia
  title: Module 6 - Privacy Assessment & Data Dictionary
  type: module
  module-id: module_6
- id: des_rvw
  title: 'Module 7 - Product Concept: Technical Design Review'
  type: module
  module-id: module_7
- id: prod_doc
  title: Module 8 - Product Security Documentation
  type: module
  module-id: module_8
- id: third_party
  title: Module 9 - 3rd Party Commercial Components Assessment
  type: module
  module-id: module_9


