id: app
title: New Copy
type: project
version: 0.1.13
instance-name: New Hologic Product Workflow
icon: app.png
protocol:
- hologic.npi
introduction:
  format: markdown
  template: "The goal of The Hologic Secure Product Design Program is to provide a
    Secure by Design methodology to the product engineering activities that span the
    entire product lifecycle from initial concept to product obsolescence. This allows
    the product development team to 'shift left' their security activities, allowing
    the inclusion of security features earlier in the development process. By shifting
    left, the cost to mitigate any security risk is significantly reduced.   \n"
input: []
output: []
catalog:
  category: Hologic
  vendor: Hologic
  vendor_url: http://hologic.com
  status: stub
  source_url: https://github.com/mjhillyer/GR_Apps
  description:
    short: Create a new product record.
    long: |
      New Compliance App
      ==================

      Edit this Markdown file to provide a long description of your compliance app. The contents of this file will be displayed in the GovReady-Q Compliance Apps Catalog.
  version: 0.1.13
questions:
- id: prod_metadata
  title: Module 1 - Information about the Product and the Product Team
  type: module
  module-id: module_1
- id: init_assessment
  title: Module 2 - Product Operational and Environmental Assessment
  type: module
  module-id: module_2
- id: min_requirements
  title: Module 4 - Minimum Security Requirements Assessment
  type: module
  module-id: module_4
- id: prod_controls
  title: Module 5 - Product Security Controls
  type: module
  module-id: module_5
- id: pia
  title: Module 6 - Privacy Assessment & Data Dictionary
  type: module
  module-id: module_6
- id: des_rvw
  title: 'Module 7 - Product Concept: Technical Design Review'
  type: module
  module-id: module_7
- id: prod_doc
  title: Module 8 - Product Security Documentation
  type: module
  module-id: module_8
- id: third_party
  title: Module 9 - 3rd Party Commercial Components Assessment
  type: module
  module-id: module_9
- id: post_market
  title: Module 3 - Post Market Support Plan
  type: module
  module-id: module_3
- id: sas
  title: Module 10 - Product Security Risk Assessment Summary
  type: module
  module-id: module_10
