id: app
title: New Compliance App
type: project
version: 0.1.0
icon: app.png
introduction:
  format: markdown
  template: |
    Use this app to achieve compliance.
input: []
output: []
catalog:
  title: Create New Product
  category: Hologic
  vendor: GovReady
  vendor_url: ~
  status: stub
  source_url: ~
  description:
    short: Create a new product record.
    long: >
      Edit this Markdown file to provide a long description of your compliance app.
      The contents of this file will be displayed in the GovReady-Q Compliance Apps
      Catalog.
  version: 0.1.0
questions:
- id: module_1
  title: Module 1
  type: module
  module-id: module_1
- id: module_2
  title: Module 2
  type: module
  module-id: module_2
- id: module_3
  title: Module 3
  type: module
  module-id: module_3
- id: module_4
  title: Module 4
  type: module
  module-id: module_4
- id: module_5
  title: Module 5
  type: module
  module-id: module_5
- id: module_6
  title: Module 6
  type: module
  module-id: module_6
- id: module_7
  title: Module 7
  type: module
  module-id: module_7
- id: module_8
  title: Module 8
  type: module
  module-id: module_8
- id: module_9
  title: Module 9
  type: module
  module-id: module_9
- id: module_10
  title: Module 10
  type: module
  module-id: module_10
