id: app
title: Hologic NPI Workflow
type: project
version: 0.1.2
icon: app.png
protocol:
- hologic.npi
introduction:
  format: markdown
  template: |
    Workflow to create a new product record.

input: []
output: []
catalog:
  title: New Product Workflow
  category: Hologic
  vendor: Hologic
  vendor_url: http://hologic.com
  status: stub
  source_url: https://github.com/mjhillyer/GR_Apps
  description:
    short: Create a new product record.
    long: >
      This is a workflow to create a new product entry into the prouct security manangement system.
  version: 0.1.2
  parameters:
  - id: catalog_key
    value: NIST_SP-800-53_rev4
  - id: baseline
    value: low

questions:
- id: module_1
  title: Module 1
  type: module
  module-id: module_1
- id: module_2
  title: Module 2
  type: module
  module-id: module_2
- id: module_3
  title: Module 3
  type: module
  module-id: module_3
- id: module_4
  title: Module 4
  type: module
  module-id: module_4
- id: module_5
  title: Module 5
  type: module
  module-id: module_5
- id: module_6
  title: Module 6
  type: module
  module-id: module_6
- id: module_7
  title: Module 7
  type: module
  module-id: module_7
- id: module_8
  title: Module 8
  type: module
  module-id: module_8
- id: module_9
  title: Module 9
  type: module
  module-id: module_9
- id: module_10
  title: Module 10
  type: module
  module-id: module_10
